# Generated by Django 5.2 on 2025-04-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_shape', models.CharField(max_length=100)),
                ('occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('clothing_type', models.CharField(max_length=100)),
                ('recommendations', models.JSONField()),
            ],
        ),
    ]
