# Generated by Django 5.2 on 2025-04-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalColourAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('skin_tone', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('complementary_colors', models.JSONField()),
                ('color_combinations', models.JSONField()),
            ],
        ),
    ]
