# Generated by Django 5.2 on 2025-04-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
